version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./internal/infra/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  ordersystem:
    image: golang:1.19
    container_name: ordersystem
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_started
    command: ["sh", "-c", "go mod tidy && go run ./cmd/ordersystem/main.go ./cmd/ordersystem/wire_gen.go"]
    volumes:
      - .:/app
      - ./cmd/ordersystem/.env:/app/.env
    working_dir: /app
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"